#!/bin/sh
BASE_DIR="/home/ghz/wx/"
OUT_FILE="$BASE_DIR/plots/wx.html"
DATE=`date +%T\ %Z\ %d\ %b\ %Y`

TOP="<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">
<html> <head> <title> danger! test product! </title> </head> 
<body  bgcolor=\"#000000\" text=\"#206cff\" link=\"#0099ff\" vlink=\"#00ffff\"> 
<center>
<br> Weather from Kiel (Northern Germany), uncalibrated, just playing with a raspberry pi and some adafruit kit.
<br> <br>
<br> Current Conditions (updates every ~60s):
<table borders>"

END="</table>
<br>
<img src=\"exttemp.png\"><br><br>
<img src=\"exthum.png\"><br><br>
<img src=\"pressure.png\"><br><br>
<img src=\"inttemp.png\"><br><br>
<img src=\"inthumsht.png\"><br><br>
<img src=\"pitemp.png\"><br><br>
</center>
<br> <br>
</body> </html>"

LASTLINE=` cat $BASE_DIR/data/last48h |tail -1`
LASTLINE1=` cat $BASE_DIR/data/last48h.sht |tail -1`
LASTLINE2=` cat $BASE_DIR/data/last48h.htu_ext |tail -1`
LASTLINE3=` cat $BASE_DIR/data/last48h.pitemp |tail -1`
INTTEMP=`echo $LASTLINE |awk '{print $2}'`
REL_PRESS=`echo $LASTLINE |awk '{print $4}'`
INTTEMPSHT=`echo $LASTLINE1 |awk '{print $3}'`
INTHUMSHT=`echo $LASTLINE1 |awk '{print $6}'`
EXTTEMP=`echo $LASTLINE2 |awk '{print $3}'`
EXTHUM=`echo $LASTLINE2 |awk '{print $6}'`
EXTDP=`echo $LASTLINE2 |awk '{print $10}'`
PITEMP=`echo $LASTLINE3 |awk '{printf "%.2f\n", $2/1000}'`

echo $TOP >$OUT_FILE

echo "<tr><td>Ext Temp:</td> <td>$EXTTEMP C</td> <td>Ext Humidity:</td> <td>$EXTHUM %</td></tr>" >>$OUT_FILE
echo "<tr><td>Pressure:</td> <td>$REL_PRESS kPa</td> <td>Int Temp 0:</td> <td>$INTTEMP C</td></tr>" >>$OUT_FILE
echo "<tr><td>Ext Dew Point:</td> <td>$EXTDP C</td> <td>Int Temp 1:</td> <td>$INTTEMPSHT C</td></tr>" >>$OUT_FILE
echo "<tr><td>Int Humidity:</td> <td>$INTHUMSHT %</td> <td>Pi Temp:</td>  <td>$PITEMP C</td></tr>" >>$OUT_FILE
echo "<tr><td>Last Update:</td>  <td>$DATE</td></tr>" >>$OUT_FILE

echo $END >>$OUT_FILE
