#!/bin/bash
# this script is run from cron

TEMP_SRC="/sys/class/thermal/thermal_zone0/temp"
DATA_DIR="/home/ghz/wx/data"

(date +%Y%m%d%H%M%S; cat $TEMP_SRC) |paste - - >> $DATA_DIR/pi_temp.`date +%Y%m%d`
