#!/bin/bash
# this script is run from cron

OVER_DIR="/home/ghz/wx"
LOCK="$OVER_DIR/plots/LOCK.wx"

[ -e $LOCK ] && {
	echo "$0: lock exists" | logger
	exit 1
}

# lock is also checked for and deleted on boot, in case of a crash
touch $LOCK

$OVER_DIR/sensor_data_grab.py
$OVER_DIR/wx.go

# try not to loose 20 min of data from hard reboots
sync

rsync -e "ssh -q" --timeout=60 -ur $OVER_DIR/* wx1@darkdata.org:/wx1/ 2>/dev/null

rm $LOCK
