#!/bin/bash
# this script is run from cron

OVER_DIR="/home/ghz/wx"

$OVER_DIR/sensor_data_grab.py

$OVER_DIR/wx.go
$OVER_DIR/particle/graph

rsync -e "ssh -q" --timeout=60 -ur $OVER_DIR/* wx@darkdata.org:/wx/test/ 2>/dev/null
