#!/usr/bin/python -u

import RPi.GPIO as GPIO
import time
import datetime

data_f_n_plate = "/home/ghz/wx/particle/data/data"

count = 0

time0 = time.time()
time1 = time.time()

GPIO.setmode(GPIO.BCM)

GPIO.setup(17, GPIO.IN, pull_up_down=GPIO.PUD_UP)

def write_out(ts, data):
	f_ts = ts[0:8]
	out_file_fd = open(data_f_n_plate+'.'+f_ts, 'a')
	out_file_fd.write(data)
	out_file_fd.close()

def trigger_count(channel):
	global count, time0, time1

	time1 = time.time()
	count += 1
	time2 = time1 - time0

	if(time2 > 60):
		ts =  datetime.datetime.fromtimestamp(time1).strftime("%Y%m%d%H%M%S")
		dat_string = "%s %.2f cpm\n" % (ts, count/(60/time2))
		write_out(ts, dat_string)
		count = 0
		time0 = time.time()

GPIO.add_event_detect(17, GPIO.FALLING, callback=trigger_count, bouncetime=20)

try:
	while True:
		time.sleep(1)

except KeyboardInterrupt:
	GPIO.cleanup()   # clean up on ctrl c.
