#!/bin/sh
BASE_DIR="/home/ghz/wx/particle"
DATA_DIR="$BASE_DIR/data"
OUT_FILE="$BASE_DIR/plots/particles.html"
DATE=`date +%FT%TZ`
TDATE=`date +%Y%m%d`

TOP="<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">
<html> <head> <title> slackology.net particle weather </title> </head> 
<body  bgcolor=\"#000000\" text=\"#206cff\" link=\"#0099ff\" vlink=\"#00ffff\"> 
<center> <h1>Background Radiation.</h1>
<a href="http://slackology.net/wxnotes.html#pw">More info on the weather notes page.</a><br>
<br> Current Conditions (updates every ~60s):
<table borders>"

END="</table>
<br>
<img src=\"http://wx.slackology.net/particle/plots/particle_cpm_8.png\"><br><br>
<img src=\"http://wx.slackology.net/particle/plots/particle_cpm_8_avg.png\"><br><br>
<img src=\"http://wx.slackology.net/particle/plots/particle_cpm_24.png\"><br><br>
<img src=\"http://wx.slackology.net/particle/plots/particle_cpm_24_avg.png\"><br><br>
<img src=\"http://wx.slackology.net/particle/plots/particle_cpm_DA.45.png\"><br><br>
<img src=\"http://wx.slackology.net/particle/plots/particle_cpm_DA.png\"><br><br>
<img src=\"http://wx.slackology.net/particle/plots/particle_cpm_MA.png\"><br><br>
</center>
<br> <br>
</body> </html>"

LASTLINE=` cat $DATA_DIR/data.$TDATE |tail -1`
CPM=`echo $LASTLINE |awk '{printf("%.2f", $2*1000/108)}'`

LASTLINEAVG=` cat $DATA_DIR/data.8.avg |tail -1`
AVG_CPM=`echo $LASTLINEAVG |awk '{printf("%.2f", $2*1000/108)}'`

LASTLINEAVG=` cat $DATA_DIR/data.8.avg.64 |tail -1`
AVG_CPM64=`echo $LASTLINEAVG |awk '{printf("%.2f", $2*1000/108)}'`

echo $TOP >$OUT_FILE

echo "<tr><td>Activity for Last ~1m:</td> <td>$CPM nGy/h</td></tr>" >>$OUT_FILE
echo "<tr><td>Average for Last ~16m:</td> <td>$AVG_CPM nGy/h</td></tr>" >>$OUT_FILE
echo "<tr><td>Average for Last ~64m:</td> <td>$AVG_CPM64 nGy/h</td></tr>" >>$OUT_FILE
echo "<tr><td>Last Update:</td> <td>$DATE</td></tr>" >>$OUT_FILE

echo $END >>$OUT_FILE
