#!/bin/sh
# see http://slackology.net/wxnotes.html for more info

TD="data"
BASE_DIR="/home/ghz/wx/particle"
DATA_DIR="$BASE_DIR/data"
PLOT_DIR="$BASE_DIR/plots"
LOCK="$BASE_DIR/LOCK.particle"
AVG_FILTER=$BASE_DIR/box_avg_filter
AVG_F_64=$BASE_DIR/box_avg_f_64
DAY_AVG=$BASE_DIR/day_avg
NSAMP=4000
OF="$DATA_DIR/$TD"
DA_OF="$DATA_DIR/data.day_avg"
MA_OF="$DATA_DIR/data.month_avg"

#from cronjob
FLAG="$BASE_DIR/CRONFLAG"
FLAG_MO="$BASE_DIR/CRONFLAG_MO"

#cd $BASE_DIR || exit 1
cd $PLOT_DIR || exit 1

[ -e $LOCK ] && {
	echo "oh lock noes"
	exit 1
}

touch $LOCK

DY=`date +%Y`
DATE=`date +%Y%m%d`
DATE8H=`date -d "-8 hours" +%Y%m%d%H`
YDATE=`date -d "-1 day" +%Y%m%d`
YYDATE=`date -d "-2 day" +%Y%m%d`
YDATEH=`date -d "-1 day" +%Y%m%d%H`
YMDATE=`date -d "-1 month" +%Y%m`

PAT="^$DY([0-9]{10}) [0-9]*\.[0-9]* cpm$"
PAT1="^$YMDATE([0-9]{8}) [0-9]*\.[0-9]* cpm$"

TDS0="cat $DATA_DIR/data.$YYDATE $DATA_DIR/data.$YDATE $DATA_DIR/data.$DATE | egrep -a \"$PAT\""
TDS1="cat $DATA_DIR/data.$YDATE $DATA_DIR/data.$DATE | egrep -a \"$PAT\""
TDS3="cat $DATA_DIR/data.$YMDATE* | egrep -a \"$PAT1\""

TD_DUMP0="eval $TDS0"
TD_DUMP1="eval $TDS1"
TD_DUMP3="eval $TDS3"

if [ -e $FLAG ]; then
	(echo "$YDATE"; cat $DATA_DIR/data.$YDATE |$DAY_AVG) | paste - - >> $DA_OF
	rm $FLAG
fi
	
if [ -e $FLAG_MO ]; then
	(echo "$YMDATE"; $TD_DUMP3 |$DAY_AVG) | paste - - >> $MA_OF
	rm $FLAG_MO
fi
	
$TD_DUMP0 | grep -A $NSAMP $YDATEH > $OF.24 || $TD_DUMP0 > $OF.24

$TD_DUMP0 | $AVG_FILTER | grep -A $NSAMP $YDATEH > $OF.24.avg || $TD_DUMP0 | $AVG_FILTER > $OF.24.avg
$TD_DUMP0 | $AVG_F_64 | grep -A $NSAMP $YDATEH > $OF.24.avg.64 || $TD_DUMP0 | $AVG_F_64 > $OF.24.avg.64

$TD_DUMP1 | grep -A $NSAMP $DATE8H > $OF.8 || $TD_DUMP1 > $OF.8

$TD_DUMP1 | $AVG_FILTER | grep -A $NSAMP $DATE8H > $OF.8.avg || $TD_DUMP1 | $AVG_FILTER > $OF.8.avg
$TD_DUMP1 | $AVG_F_64 | grep -A $NSAMP $DATE8H > $OF.8.avg.64 || $TD_DUMP1 | $AVG_F_64 > $OF.8.avg.64

cat $DA_OF |tail -n 45 > $DA_OF.45

$BASE_DIR/gen_index

gnuplot -e "OF='$OF';DAF='$DA_OF';MAF='$MA_OF'" $BASE_DIR/particle_specs.gnuplot

rm $LOCK
